# Generated by Django 4.0.4 on 2022-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_bookmodel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='img_src',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='votes_count',
            field=models.IntegerField(editable=False),
        ),
    ]
