# Generated by Django 4.0.4 on 2022-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_book_user_book_img_src_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='votes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
