# Generated by Django 4.0.4 on 2022-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bookreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.FloatField(default=0, editable=False, max_length=5),
        ),
    ]
