# Generated by Django 4.0.4 on 2022-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_bookreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
